### ISSUE TITLE
为什么不使用maven构建？

### ISSUE THREAD

**Issue by zhaohfup** [rongcloud/server-sdk-java#15]
maven构建使用SDK的只需要pom文件引用，大部分的项目都是maven构建的。如果SDK升级，pom只需要引用相应的版本

**Comment by CodinngLee** [comment]
同意，我们还要拿回来编译到自己项目里，痛苦。这不是现代化包管理方法

**Comment by koly23** [comment]
实在是太同意了。目录结构都不是标准的java项目的结构。

**Comment by canghailan** [comment]
嗯，的确不方便，我提了一个添加maven支持的pull request， #18 
或者clone我的fork，自己mvn package deploy到私有maven仓库里。
[https://github.com/canghailan/server-sdk-java](https://github.com/canghailan/server-sdk-java)

**Comment by chaoohua** [comment]
目前最新的 3.0 版本已经支持 meavn,gradle 和中央仓库获取 JAR 方式

**Comment by yuwnloyblog** [comment]
Maven 仓库地址：https://mvnrepository.com/artifact/cn.rongcloud.im/server-sdk-java
