### ISSUE TITLE
mvn打包后jar内resource读取不到修改

### ISSUE THREAD

**Issue by lx626195969** [rongcloud/server-sdk-java#21]
`io.rong.util.JsonUtil.getJsonObject`方法中
`reader =new BufferedReader( new InputStreamReader(new FileInputStream(JSONFILE+path+jsonName)));`
应该为
`reader = new BufferedReader(new InputStreamReader(JsonUtil.class.getResourceAsStream("/jsonsource/" + path + jsonName)));`

**Comment by chaoohua** [comment]
您好感谢您提供建议，已经在3.0.1版本修复了此问题。
