### ISSUE TITLE
java.io.FileNotFoundException

### ISSUE THREAD

**Issue by MrYZD** [rongcloud/server-sdk-java#22]
打包成jar包后，json 文件读取不到。
java.io.FileNotFoundException: file:\C:\Users\15052\.m2\repository\com\rcloud\server-sdk-java\3.0.0\server-sdk-java-3.0.0.jar!\jsonsource\group\api.json (文件名、目录名或卷标语法不正确。)

**Comment by chaoohua** [comment]
您好感谢您提供建议，目前此问题已在新版本中修复
