### ISSUE TITLE
消息模块发送聊天室消息3.0.1版本bug

### ISSUE THREAD

**Issue by feixz** [rongcloud/server-sdk-java#24]
![image](https://user-images.githubusercontent.com/16345433/44191299-4b2beb00-a15d-11e8-8d0b-9f82f7596281.png)
```java
public String[] getTargetId() {
        return super.getTargetId();
    }
```
array.toString()

**Comment by chaoohua** [comment]
您好感谢您提供建议，此问题已在主线分支修复。
