### ISSUE TITLE
fastjson1.2.4无法下载依赖

### ISSUE THREAD

**Issue by SkateLiu** [rongcloud/server-sdk-java#25]
![image](https://user-images.githubusercontent.com/16147192/46597839-63dccf80-cb14-11e8-9819-d4601bcd9d41.png)

**Comment by SkateLiu** [comment]
这个依赖有点问题

**Comment by chaoohua** [comment]
您好，目前遇到的问题是此依赖版本的 jar 包不能够下载么。请您检查下您的项目里面是否有此jar包冲突，做下相关排除
