### ISSUE TITLE
通过http请求发送自定义消息

### ISSUE THREAD

**Issue by jerrymousefxd** [rongcloud/server-sdk-java#26]
通过http请求发送自定义消息，如何将自定义的objectName注册到融云消息类型中去，目前问题：可以发送成功，进入历史消息，但是不可以被实时监听到。

**Comment by yuwnloyblog** [comment]
> 通过http请求发送自定义消息，如何将自定义的objectName注册到融云消息类型中去，目前问题：可以发送成功，进入历史消息，但是不可以被实时监听到。

您好，不可以实时被监听到，指的是客户端消息监听吧， 自定义的objectName需要您注册在客户端中。
Android ：https://www.rongcloud.cn/docs/android.html#message_customize_new
iOS ： https://www.rongcloud.cn/docs/ios.html#message_customize_new

**Comment by jerrymousefxd** [comment]
目前测试的是web h5端，自定义消息，发送的时候多个接收的融云id，（一个用户向**多个**用户发起单聊），自定义消息的pushdata已经存上数据，前端h5也加了监听，但是不能被实时监听到；一个用户向**一个**用户发起单聊的时候是可以监听到的。
