### ISSUE TITLE
系统消息接口，接收者字段校验逻辑 Bug

### ISSUE THREAD

**Issue by yuwnloyblog** [rongcloud/server-sdk-java#27]
示例：
public class Test {
	private static final TxtMessage txtMessage = new TxtMessage("hello", "helloExtra");
	private static final String PATH = "message/system";
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		String[] targetIds = new String[100];
		
		for(int i=0;i<10;i++) {
			targetIds[i] = "test"+i;
		}
		
		SystemMessage systemMessage = new SystemMessage().setSenderId("usetId").setTargetId(targetIds)
				.setObjectName(txtMessage.getType()).setContent(txtMessage).setPushContent("this is a push")
				.setPushData("{'pushData':'hello'}").setIsPersisted(0).setIsCounted(0).setContentAvailable(0);
	
		String code = CommonUtil.checkFiled(systemMessage,PATH,CheckMethod.PUBLISH);
		System.out.println(code);
	}

}

返回 ：
{"msg":"TargetId 长度超限, TargetId >= 1 且 TargetId <= 64","code":"20003"}

**Comment by chaoohua** [comment]
您好, 此问题已经在 Master 分支更改, 按照每种会话类型校验.
