### ISSUE TITLE
version 3.0.2发送私聊消息报错

### ISSUE THREAD

**Issue by nicholasbobo** [rongcloud/server-sdk-java#28]
跟踪代码发现是读取api.json文件乱码导致解析为json对象时报错，io.rong.JsonUtil.getJsonObject(String path, String jsonName)方法中，读取文件的InputStreamReader应该要调用带字符编码的构造函数才对，望尽快修复

**Comment by chaoohua** [comment]
您好 感谢您向我们提供问题，此问题已经在 master 分支修复。您可以获取 master 最新代码，通过 Meavn 打包构建。
