### ISSUE TITLE
什么时候增加用户Tag和消息Push等新API的支持

### ISSUE THREAD

**Issue by hanyou** [rongcloud/server-sdk-java#29]
在SDK中请增加一些新的API的支持。

**Comment by chaoohua** [comment]
您好，用户 Tag 和消息 Push 等新 API  会在下个版本中支持，同时 SDK 会在最近更新。感谢您提供的意见和建议。

**Comment by qq592304796** [comment]
提交了一个pull request #30
里面加了Tag和Push的支持

**Comment by chiquanqing-214** [comment]
谢谢您分享，3.0.4 已经添加相应功能
