### ISSUE TITLE
短信模块的sdk在什么地方。

### ISSUE THREAD

**Issue by JohneySen** [rongcloud/server-sdk-java#32]
我看演示也没有呢？

**Comment by JohneySen** [comment]
没人维护吗？？

**Comment by chiquanqing-214** [comment]
短信服务相关示例还未添加到 SDK 中，后续我们会逐步完善，暂时可以参考 [【融云短信服务开发指南】](https://www.rongcloud.cn/docs/sms_service.html#summary)
