### ISSUE TITLE
maven下载下来的3.0.2 jar为什么群定向消息功能 toUserId这个字段没了

### ISSUE THREAD

**Issue by yinian-R** [rongcloud/server-sdk-java#33]
群定向消息功能
io.rong.models.message.GroupMessage toUserId 这个字段没有
io.rong.methods.message.group.Group.sendDirection 这个方法也没

我用了阿里云的仓库

api文档：
https://www.rongcloud.cn/docs/server_sdk_api/message/group.html#sendDirection

**Comment by yinian-R** [comment]
直接从github README.md下载的Jar也没这个字段和方法

**Comment by chiquanqing-214** [comment]
已更新，请使用 3.0.3 以上版本
