### ISSUE TITLE
io.rong.models.push.PlatformNotification

### ISSUE THREAD

**Issue by faithion** [rongcloud/server-sdk-java#43]
io.rong.models.push.PlatformNotification的extra字段能否修改泛型为Map<String,Object>.
不然不能传对象,只能把对象转为jsonString传递,这样就会有一些问题.很不方便

**Comment by Hello-world-** [comment]
> io.rong.models.push.PlatformNotification的extra字段能否修改泛型为Map<String,Object>. 不然不能传对象,只能把对象转为jsonString传递,这样就会有一些问题.很不方便

server sdk 是对 server api的封装
该字段api中定义的是String类型的键值对
类型不固定后续会有json解析风险，辛苦您转义一下
