### ISSUE TITLE
这SDK设计就是个错误

### ISSUE THREAD

**Issue by xlpxxx** [rongcloud/server-sdk-java#50]
发27条，漏3条，说的实时推送确认机制。
结果呢，服务器根本不管确认机制，主动推送几率和中彩票差不多。
每条消息都是基于时间戳被动拉取的，也就是说，对方系统时间出问题，你发的消息也全部都漏掉。
队列数据拉完之后，你再次发起拉取请求，此时你拉不到任何消息，也没有任何反应。
此时数据就会堆积，下一次拉取才会一起拉回来，假设用户不发消息了，那么条消息永远就沉在海底了

**够辣鸡**
**够辣鸡**
**够辣鸡**

**Comment by jujunchen** [comment]
哦，no

**Comment by Hello-world-** [comment]
这是server sdk repo 请求的server api 异步发送，
不涉及拉取逻辑，即使说客户端也不是这么做的

1.有定时拉取离线机制
2.单群聊有直发和通知拉取逻辑，聊天室只有拉取机制实现不同
3.拉取用的时间戳不是手机本地时间戳，而是服务器下发的上一条消息的时间戳
