### ISSUE TITLE
请问实时通信，这个支持socket-io吗？就是我不是很理解实时聊天这个过程。

### ISSUE THREAD

**Issue by Flyooofly** [rongcloud/server-sdk-java#52]
请问实时聊天时我这边发请求是以什么形式发起呢？我当前想用socket-io发起，那融云服务器端是否能接收这种请求呢？小白不懂，麻烦大佬告知。

**Comment by ccfish86** [comment]
使用对应的应用运行环境（安卓、IOS、web、小程序、flutter etc.）下对应的SDK

**Comment by Hello-world-** [comment]
> 请问实时聊天时我这边发请求是以什么形式发起呢？我当前想用socket-io发起，那融云服务器端是否能接收这种请求呢？小白不懂，麻烦大佬告知。

该repo 为server sdk 
您说的实时聊天请求一般从客户端直接发起
可以参考:https://doc.rongcloud.cn/im/Android/5.X/prepare
