### ISSUE TITLE
下面的文档里写的集成版本有误

### ISSUE THREAD

**Issue by ideallain** [rongcloud/server-sdk-java#54]
这个SDK版本是错的，2021-1-4，maven中央仓库里只能查到3.1.15，更新日期是17-Dec-2020，但是下面的集成一栏里悍然写着3.2.0，不知道为啥
![%%MVT8GXD9L4SFP2CF2)NGB](https://user-images.githubusercontent.com/26687902/103518618-0f6d5980-4eaf-11eb-9bcd-abc44552135d.png)
![_7JL( 6IPGKKC%3P$W3D~~E](https://user-images.githubusercontent.com/26687902/103518659-201dcf80-4eaf-11eb-8c0c-126f961c86ac.png)

**Comment by Hello-world-** [comment]
问题已处理，maven中央仓库更新有延迟，下次注意
