### ISSUE TITLE
最新版本号和maven仓库不一致，还有SDK中的方法不全

### ISSUE THREAD

**Issue by MrzZhang** [rongcloud/server-sdk-java#55]
发现问题：
1.最新版本号和maven仓库不一致
2.还有SDK中的方法的示例不全，比如：全体成员禁言白名单 等等，还有好多，不一一列

**Comment by Hello-world-** [comment]
1.版本号问题应该已经修复
2.方法示例只是方法调用示例，一般请求大同小异
