### ISSUE TITLE
`user.tag`下相关的接口

### ISSUE THREAD

**Issue by ccfish86** [rongcloud/server-sdk-java#67]
现在只有set,get,batchSet接口
但通过这些接口，设置Tag的话，会覆盖现有用户已有的Tag，要么需要提前查询然后手动合并再调用set。
单个用户的还好办，但批量用户的话，会比较麻烦，

**可以追加几个接口吗？**
1. 添加Tag
2. 删除Tag
3. 批量（用户）添加Tag

**Comment by Hello-world-** [comment]
感谢您的反馈，已同步产品侧
